fix for Python 3.9+
pattern-inc/cynetworkx pull request #8
Opened 2022-10-16 07:41 UTC by drensin

fractions.gcd() was deprecated in Python 3.9 for math.gcd().  This fix looks for fractions.gcd() and if it can't find it, get gcd() from math

2023-04-13 14:23 UTC, PetrusV83 requested changes

2023-04-13 14:23 UTC, PetrusV83 commented on cynetworkx/algorithms/dag.py
> -from fractions import gcd
from math import gcd

2023-04-17 06:39 UTC, BjornFJohansson commented
Cynetworkx was probably abandoned.

2023-05-10 20:10 UTC, awestley approved these changes

2023-05-10 20:10 UTC, merged

2023-05-11 05:44 UTC, BjornFJohansson commented
I was wrong!